//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minesweeper.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    public sealed partial class Statistics : global::System.Configuration.ApplicationSettingsBase
    {

        private static Statistics defaultInstance = ((Statistics)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Statistics())));

        public static Statistics Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Mini_GamesWon
        {
            get
            {
                return ((int)(this["Mini_GamesWon"]));
            }
            set
            {
                this["Mini_GamesWon"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Mini_GamesLost
        {
            get
            {
                return ((int)(this["Mini_GamesLost"]));
            }
            set
            {
                this["Mini_GamesLost"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Mini_TotalMines
        {
            get
            {
                return ((int)(this["Mini_TotalMines"]));
            }
            set
            {
                this["Mini_TotalMines"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan Mini_TotalTime
        {
            get
            {
                return ((global::System.TimeSpan)(this["Mini_TotalTime"]));
            }
            set
            {
                this["Mini_TotalTime"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan Mini_ShortTime
        {
            get
            {
                return ((global::System.TimeSpan)(this["Mini_ShortTime"]));
            }
            set
            {
                this["Mini_ShortTime"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Beginner_GamesWon
        {
            get
            {
                return ((int)(this["Beginner_GamesWon"]));
            }
            set
            {
                this["Beginner_GamesWon"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Beginner_GamesLost
        {
            get
            {
                return ((int)(this["Beginner_GamesLost"]));
            }
            set
            {
                this["Beginner_GamesLost"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Beginner_TotalMines
        {
            get
            {
                return ((int)(this["Beginner_TotalMines"]));
            }
            set
            {
                this["Beginner_TotalMines"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan Beginner_TotalTime
        {
            get
            {
                return ((global::System.TimeSpan)(this["Beginner_TotalTime"]));
            }
            set
            {
                this["Beginner_TotalTime"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan Beginner_ShortTime
        {
            get
            {
                return ((global::System.TimeSpan)(this["Beginner_ShortTime"]));
            }
            set
            {
                this["Beginner_ShortTime"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Intermediate_GamesWon
        {
            get
            {
                return ((int)(this["Intermediate_GamesWon"]));
            }
            set
            {
                this["Intermediate_GamesWon"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Intermediate_GamesLost
        {
            get
            {
                return ((int)(this["Intermediate_GamesLost"]));
            }
            set
            {
                this["Intermediate_GamesLost"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Intermediate_TotalMines
        {
            get
            {
                return ((int)(this["Intermediate_TotalMines"]));
            }
            set
            {
                this["Intermediate_TotalMines"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan Intermediate_TotalTime
        {
            get
            {
                return ((global::System.TimeSpan)(this["Intermediate_TotalTime"]));
            }
            set
            {
                this["Intermediate_TotalTime"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan Intermediate_ShortTime
        {
            get
            {
                return ((global::System.TimeSpan)(this["Intermediate_ShortTime"]));
            }
            set
            {
                this["Intermediate_ShortTime"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Expert_GamesWon
        {
            get
            {
                return ((int)(this["Expert_GamesWon"]));
            }
            set
            {
                this["Expert_GamesWon"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Expert_GamesLost
        {
            get
            {
                return ((int)(this["Expert_GamesLost"]));
            }
            set
            {
                this["Expert_GamesLost"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Expert_TotalMines
        {
            get
            {
                return ((int)(this["Expert_TotalMines"]));
            }
            set
            {
                this["Expert_TotalMines"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan Expert_TotalTime
        {
            get
            {
                return ((global::System.TimeSpan)(this["Expert_TotalTime"]));
            }
            set
            {
                this["Expert_TotalTime"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan Expert_ShortTime
        {
            get
            {
                return ((global::System.TimeSpan)(this["Expert_ShortTime"]));
            }
            set
            {
                this["Expert_ShortTime"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Custom_GamesWon
        {
            get
            {
                return ((int)(this["Custom_GamesWon"]));
            }
            set
            {
                this["Custom_GamesWon"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Custom_GamesLost
        {
            get
            {
                return ((int)(this["Custom_GamesLost"]));
            }
            set
            {
                this["Custom_GamesLost"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Custom_TotalMines
        {
            get
            {
                return ((int)(this["Custom_TotalMines"]));
            }
            set
            {
                this["Custom_TotalMines"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan Custom_TotalTime
        {
            get
            {
                return ((global::System.TimeSpan)(this["Custom_TotalTime"]));
            }
            set
            {
                this["Custom_TotalTime"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan Custom_ShortTime
        {
            get
            {
                return ((global::System.TimeSpan)(this["Custom_ShortTime"]));
            }
            set
            {
                this["Custom_ShortTime"] = value;
            }
        }
    }
}
