//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minesweeper.Properties.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minesweeper.Properties.Languages.de_DE", typeof(de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Projekt auf GitHub ansehen.
        /// </summary>
        internal static string AboutViewOnGithub {
            get {
                return ResourceManager.GetString("AboutViewOnGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓.
        /// </summary>
        internal static string AppConfirmButton {
            get {
                return ResourceManager.GetString("AppConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es läuft gerade ein Spiel. Möchten Sie wirklich das Spiel verlassen?.
        /// </summary>
        internal static string AppConfirmExitText {
            get {
                return ResourceManager.GetString("AppConfirmExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        internal static string AppConfirmExitTitle {
            get {
                return ResourceManager.GetString("AppConfirmExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es läuft gerade ein Spiel. Willst du wirklich ein neues Spielfeld erstellen?.
        /// </summary>
        internal static string AppConfirmNewGameText {
            get {
                return ResourceManager.GetString("AppConfirmNewGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Spielfeld erstellen.
        /// </summary>
        internal static string AppConfirmNewGameTitle {
            get {
                return ResourceManager.GetString("AppConfirmNewGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Manuel Klär
        ///© Max Mitterböck.
        /// </summary>
        internal static string AppCopyright {
            get {
                return ResourceManager.GetString("AppCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💣.
        /// </summary>
        internal static string AppEmoji {
            get {
                return ResourceManager.GetString("AppEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string AppNextButton {
            get {
                return ResourceManager.GetString("AppNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string AppPreviousButton {
            get {
                return ResourceManager.GetString("AppPreviousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        internal static string AppProgressText {
            get {
                return ResourceManager.GetString("AppProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} / {2}.
        /// </summary>
        internal static string AppProgressTextEmoji {
            get {
                return ResourceManager.GetString("AppProgressTextEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string AppTextEmoji {
            get {
                return ResourceManager.GetString("AppTextEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minesweeper.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über.
        /// </summary>
        internal static string AppTitleAbout {
            get {
                return ResourceManager.GetString("AppTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerdefiniert.
        /// </summary>
        internal static string AppTitleCustomGame {
            get {
                return ResourceManager.GetString("AppTitleCustomGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endergebniss.
        /// </summary>
        internal static string AppTitleEndResult {
            get {
                return ResourceManager.GetString("AppTitleEndResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string AppTitleSettings {
            get {
                return ResourceManager.GetString("AppTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistiken.
        /// </summary>
        internal static string AppTitleStatistics {
            get {
                return ResourceManager.GetString("AppTitleStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie wird gespielt?.
        /// </summary>
        internal static string AppTitleTutorial {
            get {
                return ResourceManager.GetString("AppTitleTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen zu {0}.
        /// </summary>
        internal static string AppTitleWelcome {
            get {
                return ResourceManager.GetString("AppTitleWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Höhe.
        /// </summary>
        internal static string CustomHeight {
            get {
                return ResourceManager.GetString("CustomHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipps.
        /// </summary>
        internal static string CustomHints {
            get {
                return ResourceManager.GetString("CustomHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minen.
        /// </summary>
        internal static string CustomMines {
            get {
                return ResourceManager.GetString("CustomMines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breite.
        /// </summary>
        internal static string CustomWidth {
            get {
                return ResourceManager.GetString("CustomWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⊞.
        /// </summary>
        internal static string EmojiBoard {
            get {
                return ResourceManager.GetString("EmojiBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💣.
        /// </summary>
        internal static string EmojiBomb {
            get {
                return ResourceManager.GetString("EmojiBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🕑.
        /// </summary>
        internal static string EmojiClock {
            get {
                return ResourceManager.GetString("EmojiClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚑.
        /// </summary>
        internal static string EmojiFlag {
            get {
                return ResourceManager.GetString("EmojiFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :).
        /// </summary>
        internal static string EmojiHappy {
            get {
                return ResourceManager.GetString("EmojiHappy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⌨.
        /// </summary>
        internal static string EmojiKeyboard {
            get {
                return ResourceManager.GetString("EmojiKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡.
        /// </summary>
        internal static string EmojiLightBulb {
            get {
                return ResourceManager.GetString("EmojiLightBulb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎉.
        /// </summary>
        internal static string EmojiPartyPopper {
            get {
                return ResourceManager.GetString("EmojiPartyPopper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to II.
        /// </summary>
        internal static string EmojiPause {
            get {
                return ResourceManager.GetString("EmojiPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📈.
        /// </summary>
        internal static string EmojiPerformance {
            get {
                return ResourceManager.GetString("EmojiPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▷.
        /// </summary>
        internal static string EmojiPlay {
            get {
                return ResourceManager.GetString("EmojiPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string EmojiQuestion {
            get {
                return ResourceManager.GetString("EmojiQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EmojiStop {
            get {
                return ResourceManager.GetString("EmojiStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚔.
        /// </summary>
        internal static string EmojiSwords {
            get {
                return ResourceManager.GetString("EmojiSwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verloren.
        /// </summary>
        internal static string GameLost {
            get {
                return ResourceManager.GetString("GameLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewonnen.
        /// </summary>
        internal static string GameWon {
            get {
                return ResourceManager.GetString("GameWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel.
        /// </summary>
        internal static string MenuGame {
            get {
                return ResourceManager.GetString("MenuGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laden.
        /// </summary>
        internal static string MenuLoad {
            get {
                return ResourceManager.GetString("MenuLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        internal static string MenuNew {
            get {
                return ResourceManager.GetString("MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistiken.
        /// </summary>
        internal static string MenuStatistics {
            get {
                return ResourceManager.GetString("MenuStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string MenuTutorial {
            get {
                return ResourceManager.GetString("MenuTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel pausiert.
        /// </summary>
        internal static string OverlayGamePaused {
            get {
                return ResourceManager.GetString("OverlayGamePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicke um zu beginnen.
        /// </summary>
        internal static string OverlayGameStopped {
            get {
                return ResourceManager.GetString("OverlayGameStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfänger.
        /// </summary>
        internal static string PresetBeginner {
            get {
                return ResourceManager.GetString("PresetBeginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerdefiniert.
        /// </summary>
        internal static string PresetCustom {
            get {
                return ResourceManager.GetString("PresetCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experte.
        /// </summary>
        internal static string PresetExpert {
            get {
                return ResourceManager.GetString("PresetExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortgeschritten.
        /// </summary>
        internal static string PresetIntermediate {
            get {
                return ResourceManager.GetString("PresetIntermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klein.
        /// </summary>
        internal static string PresetMini {
            get {
                return ResourceManager.GetString("PresetMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akzentfarbe:.
        /// </summary>
        internal static string SettingsAccentColor {
            get {
                return ResourceManager.GetString("SettingsAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hintergrundfarbe:.
        /// </summary>
        internal static string SettingsBackgroundColor {
            get {
                return ResourceManager.GetString("SettingsBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurücksetzen.
        /// </summary>
        internal static string SettingsButtonReset {
            get {
                return ResourceManager.GetString("SettingsButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen.
        /// </summary>
        internal static string SettingsButtonShow {
            get {
                return ResourceManager.GetString("SettingsButtonShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applikation.
        /// </summary>
        internal static string SettingsCategoryApp {
            get {
                return ResourceManager.GetString("SettingsCategoryApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel.
        /// </summary>
        internal static string SettingsCategoryGame {
            get {
                return ResourceManager.GetString("SettingsCategoryGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        internal static string SettingsCategoryUI {
            get {
                return ResourceManager.GetString("SettingsCategoryUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardvoreinstellung:.
        /// </summary>
        internal static string SettingsDefaultPreset {
            get {
                return ResourceManager.GetString("SettingsDefaultPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache:.
        /// </summary>
        internal static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen zurücksetzen:.
        /// </summary>
        internal static string SettingsResetSettings {
            get {
                return ResourceManager.GetString("SettingsResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistiken zurücksetzen:.
        /// </summary>
        internal static string SettingsResetStatistics {
            get {
                return ResourceManager.GetString("SettingsResetStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommensdialog anzeigen:.
        /// </summary>
        internal static string SettingsShowWelcomeDialog {
            get {
                return ResourceManager.GetString("SettingsShowWelcomeDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doppelklick zum Öffnen des Farbauswahlfensters.
        /// </summary>
        internal static string SettingsTooltipColorChooser {
            get {
                return ResourceManager.GetString("SettingsTooltipColorChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Durchschnittszeit: {1}.
        /// </summary>
        internal static string StatisticsCategoryAverageTime {
            get {
                return ResourceManager.GetString("StatisticsCategoryAverageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Spiele: {1}.
        /// </summary>
        internal static string StatisticsCategoryGames {
            get {
                return ResourceManager.GetString("StatisticsCategoryGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Niederlagen: {1}.
        /// </summary>
        internal static string StatisticsCategoryLost {
            get {
                return ResourceManager.GetString("StatisticsCategoryLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Minen: {1}.
        /// </summary>
        internal static string StatisticsCategoryMines {
            get {
                return ResourceManager.GetString("StatisticsCategoryMines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Leistung: {1}%.
        /// </summary>
        internal static string StatisticsCategoryPerformance {
            get {
                return ResourceManager.GetString("StatisticsCategoryPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Kürzeste Zeit: {1}.
        /// </summary>
        internal static string StatisticsCategoryShortestTime {
            get {
                return ResourceManager.GetString("StatisticsCategoryShortestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Gesamte Zeit: {1}.
        /// </summary>
        internal static string StatisticsCategoryTotalTime {
            get {
                return ResourceManager.GetString("StatisticsCategoryTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Siege: {1}.
        /// </summary>
        internal static string StatisticsCategoryWon {
            get {
                return ResourceManager.GetString("StatisticsCategoryWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allgemein.
        /// </summary>
        internal static string StatisticsPageGeneral {
            get {
                return ResourceManager.GetString("StatisticsPageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Spieler kann Tipps verwenden, um ein zufälliges Feld aufzudecken, das eine Mine enthält. Dies kann in Situationen hilfreich sein, in denen der Spieler nicht weiß, welche Felder er als nächstes aufdecken soll. Die Tipps sind begrenzt und sollten sparsam verwendet werden..
        /// </summary>
        internal static string TutorialPage10Description {
            get {
                return ResourceManager.GetString("TutorialPage10Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipps.
        /// </summary>
        internal static string TutorialPage10Title {
            get {
                return ResourceManager.GetString("TutorialPage10Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Spieler kann das Spiel jederzeit unterbrechen, indem er auf die Schaltfläche &quot;Pause&quot; klickt. Dadurch wird der Timer angehalten und der Spieler kann nicht versehentlich Felder aufdecken oder markieren. Der Spieler kann das Spiel fortsetzen, indem er auf die Schaltfläche &quot;Fortsetzen&quot; klickt..
        /// </summary>
        internal static string TutorialPage11Description {
            get {
                return ResourceManager.GetString("TutorialPage11Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause und Fortsetzen.
        /// </summary>
        internal static string TutorialPage11Title {
            get {
                return ResourceManager.GetString("TutorialPage11Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herzlichen Glückwunsch! Sie sind nun bereit, Minesweeper zu spielen. Denken Sie daran, Ihre Tipps klug einzusetzen und den Flaggenzähler im Auge zu behalten, damit keine Minen explodieren..
        /// </summary>
        internal static string TutorialPage12Description {
            get {
                return ResourceManager.GetString("TutorialPage12Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viel Erfolg!.
        /// </summary>
        internal static string TutorialPage12Title {
            get {
                return ResourceManager.GetString("TutorialPage12Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minesweeper ist ein Puzzlespiel für Einzelspieler, bei dem es darum geht, ein rechteckiges Spielfeld mit versteckten Minen zu räumen, ohne eine von ihnen zur Explosion zu bringen. Die Spieler nutzen Logik, um sichere Felder aufzudecken und potenzielle Minenstandorte zu markieren, bis das gesamte Spielfeld geräumt ist und die Position aller Minen aufgedeckt ist..
        /// </summary>
        internal static string TutorialPage1Description {
            get {
                return ResourceManager.GetString("TutorialPage1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minesweeper.
        /// </summary>
        internal static string TutorialPage1Title {
            get {
                return ResourceManager.GetString("TutorialPage1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links-Klick: Damit decken Sie ein Feld auf. Wenn das Feld eine Mine enthält, ist das Spiel vorbei. Handelt es sich um ein leeres Feld, werden alle angrenzenden leeren Felder aufgedeckt, bis eine Zahl erreicht wird. Wenn es sich um ein nummeriertes Feld handelt, wird nur dieses aufgedeckt..
        /// </summary>
        internal static string TutorialPage2Description {
            get {
                return ResourceManager.GetString("TutorialPage2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steuerung: Linksklick.
        /// </summary>
        internal static string TutorialPage2Title {
            get {
                return ResourceManager.GetString("TutorialPage2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mittelklick: Damit können Sie ein Feld mit einem Fragezeichen markieren. Dies ist nützlich, wenn Sie sich nicht sicher sind, ob das Feld eine Mine enthält..
        /// </summary>
        internal static string TutorialPage3Description {
            get {
                return ResourceManager.GetString("TutorialPage3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steuerung: Mittelklick.
        /// </summary>
        internal static string TutorialPage3Title {
            get {
                return ResourceManager.GetString("TutorialPage3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechtsklick: Hiermit können Sie ein Feld mit einer Flagge versehen. Dies zeigt an, dass das Feld eine Mine enthält. Verwenden Sie den Flaggenzähler, um zu sehen, wie viele Minen noch auf dem Spielbrett liegen..
        /// </summary>
        internal static string TutorialPage4Description {
            get {
                return ResourceManager.GetString("TutorialPage4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steuerung: Rechtsklick.
        /// </summary>
        internal static string TutorialPage4Title {
            get {
                return ResourceManager.GetString("TutorialPage4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Spielfeld besteht aus einem Gitter aus Quadraten. Einige dieser Quadrate enthalten versteckte Minen. Das Ziel des Spielers ist es, alle Felder, die keine Minen enthalten, aufzudecken, ohne Minen zu zünden. Die Anzahl der Minen ist vorgegeben und nimmt mit der Größe des Spielfelds zu..
        /// </summary>
        internal static string TutorialPage5Description {
            get {
                return ResourceManager.GetString("TutorialPage5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spielmechanik 1/3.
        /// </summary>
        internal static string TutorialPage5Title {
            get {
                return ResourceManager.GetString("TutorialPage5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn ein Feld aufgedeckt wird, ist es entweder leer oder enthält eine Zahl. Die Zahlen stehen für die Anzahl der Minen in den acht umliegenden Feldern. Steht auf einem Feld zum Beispiel die Zahl &quot;3&quot;, bedeutet das, dass sich in den acht umliegenden Feldern drei Minen befinden..
        /// </summary>
        internal static string TutorialPage6Description {
            get {
                return ResourceManager.GetString("TutorialPage6Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spielmechanik 2/3.
        /// </summary>
        internal static string TutorialPage6Title {
            get {
                return ResourceManager.GetString("TutorialPage6Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denken Sie daran, die Zahlen auf den Feldern zu verwenden, um zu erraten wo sich Minen befinden und diese nicht zu zünden!.
        /// </summary>
        internal static string TutorialPage7Description {
            get {
                return ResourceManager.GetString("TutorialPage7Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spielmechanik 3/3.
        /// </summary>
        internal static string TutorialPage7Title {
            get {
                return ResourceManager.GetString("TutorialPage7Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Spiel läuft auf Zeit, und der Timer beginnt zu zählen, sobald der Spieler auf sein erstes Feld klickt. Die Zeit des Spielers wird auf dem Spielfeld angezeigt, und das Ziel des Spielers ist es, das Spiel in der kürzest möglichen Zeit zu beenden..
        /// </summary>
        internal static string TutorialPage8Description {
            get {
                return ResourceManager.GetString("TutorialPage8Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string TutorialPage8Title {
            get {
                return ResourceManager.GetString("TutorialPage8Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Spieler kann Felder markieren, von denen er glaubt, dass sie Minen enthalten. Ein Zähler zeigt an, wie viele Flaggen der Spieler gesetzt hat und wie viele Minen noch auf dem Spielbrett liegen. Der Spieler kann diese Informationen nutzen, um sichere Vermutungen anzustellen und das Zünden von Minen zu vermeiden..
        /// </summary>
        internal static string TutorialPage9Description {
            get {
                return ResourceManager.GetString("TutorialPage9Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flaggenzähler.
        /// </summary>
        internal static string TutorialPage9Title {
            get {
                return ResourceManager.GetString("TutorialPage9Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatisch gewählte Sprache: {0}.
        /// </summary>
        internal static string WelcomeChosenLanguage {
            get {
                return ResourceManager.GetString("WelcomeChosenLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel starten.
        /// </summary>
        internal static string WelcomeStartPlayingText {
            get {
                return ResourceManager.GetString("WelcomeStartPlayingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string WelcomeTutorialText {
            get {
                return ResourceManager.GetString("WelcomeTutorialText", resourceCulture);
            }
        }
    }
}
