//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minesweeper.Properties.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minesweeper.Properties.Languages.en_US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View this project on GitHub.
        /// </summary>
        internal static string AboutViewOnGithub {
            get {
                return ResourceManager.GetString("AboutViewOnGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓.
        /// </summary>
        internal static string AppConfirmButton {
            get {
                return ResourceManager.GetString("AppConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A game is currently running. Do you really want to exit?.
        /// </summary>
        internal static string AppConfirmExitText {
            get {
                return ResourceManager.GetString("AppConfirmExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string AppConfirmExitTitle {
            get {
                return ResourceManager.GetString("AppConfirmExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A game is currently running. Do you really want to create a new board?.
        /// </summary>
        internal static string AppConfirmNewGameText {
            get {
                return ResourceManager.GetString("AppConfirmNewGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new board.
        /// </summary>
        internal static string AppConfirmNewGameTitle {
            get {
                return ResourceManager.GetString("AppConfirmNewGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Manuel Klär
        ///© Max Mitterböck.
        /// </summary>
        internal static string AppCopyright {
            get {
                return ResourceManager.GetString("AppCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💣.
        /// </summary>
        internal static string AppEmoji {
            get {
                return ResourceManager.GetString("AppEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string AppNextButton {
            get {
                return ResourceManager.GetString("AppNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string AppPreviousButton {
            get {
                return ResourceManager.GetString("AppPreviousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        internal static string AppProgressText {
            get {
                return ResourceManager.GetString("AppProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} / {2}.
        /// </summary>
        internal static string AppProgressTextEmoji {
            get {
                return ResourceManager.GetString("AppProgressTextEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string AppTextEmoji {
            get {
                return ResourceManager.GetString("AppTextEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minesweeper.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AppTitleAbout {
            get {
                return ResourceManager.GetString("AppTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string AppTitleCustomGame {
            get {
                return ResourceManager.GetString("AppTitleCustomGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End result.
        /// </summary>
        internal static string AppTitleEndResult {
            get {
                return ResourceManager.GetString("AppTitleEndResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string AppTitleSettings {
            get {
                return ResourceManager.GetString("AppTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string AppTitleStatistics {
            get {
                return ResourceManager.GetString("AppTitleStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to play?.
        /// </summary>
        internal static string AppTitleTutorial {
            get {
                return ResourceManager.GetString("AppTitleTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}.
        /// </summary>
        internal static string AppTitleWelcome {
            get {
                return ResourceManager.GetString("AppTitleWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string CustomHeight {
            get {
                return ResourceManager.GetString("CustomHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hints.
        /// </summary>
        internal static string CustomHints {
            get {
                return ResourceManager.GetString("CustomHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mines.
        /// </summary>
        internal static string CustomMines {
            get {
                return ResourceManager.GetString("CustomMines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string CustomWidth {
            get {
                return ResourceManager.GetString("CustomWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⊞.
        /// </summary>
        internal static string EmojiBoard {
            get {
                return ResourceManager.GetString("EmojiBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💣.
        /// </summary>
        internal static string EmojiBomb {
            get {
                return ResourceManager.GetString("EmojiBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🕑.
        /// </summary>
        internal static string EmojiClock {
            get {
                return ResourceManager.GetString("EmojiClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚑.
        /// </summary>
        internal static string EmojiFlag {
            get {
                return ResourceManager.GetString("EmojiFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :).
        /// </summary>
        internal static string EmojiHappy {
            get {
                return ResourceManager.GetString("EmojiHappy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⌨.
        /// </summary>
        internal static string EmojiKeyboard {
            get {
                return ResourceManager.GetString("EmojiKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡.
        /// </summary>
        internal static string EmojiLightBulb {
            get {
                return ResourceManager.GetString("EmojiLightBulb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎉.
        /// </summary>
        internal static string EmojiPartyPopper {
            get {
                return ResourceManager.GetString("EmojiPartyPopper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to II.
        /// </summary>
        internal static string EmojiPause {
            get {
                return ResourceManager.GetString("EmojiPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📈.
        /// </summary>
        internal static string EmojiPerformance {
            get {
                return ResourceManager.GetString("EmojiPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▷.
        /// </summary>
        internal static string EmojiPlay {
            get {
                return ResourceManager.GetString("EmojiPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string EmojiQuestion {
            get {
                return ResourceManager.GetString("EmojiQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EmojiStop {
            get {
                return ResourceManager.GetString("EmojiStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚔.
        /// </summary>
        internal static string EmojiSwords {
            get {
                return ResourceManager.GetString("EmojiSwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat.
        /// </summary>
        internal static string GameLost {
            get {
                return ResourceManager.GetString("GameLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory.
        /// </summary>
        internal static string GameWon {
            get {
                return ResourceManager.GetString("GameWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string MenuGame {
            get {
                return ResourceManager.GetString("MenuGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string MenuLoad {
            get {
                return ResourceManager.GetString("MenuLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string MenuNew {
            get {
                return ResourceManager.GetString("MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string MenuStatistics {
            get {
                return ResourceManager.GetString("MenuStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string MenuTutorial {
            get {
                return ResourceManager.GetString("MenuTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game paused.
        /// </summary>
        internal static string OverlayGamePaused {
            get {
                return ResourceManager.GetString("OverlayGamePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to begin.
        /// </summary>
        internal static string OverlayGameStopped {
            get {
                return ResourceManager.GetString("OverlayGameStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner.
        /// </summary>
        internal static string PresetBeginner {
            get {
                return ResourceManager.GetString("PresetBeginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string PresetCustom {
            get {
                return ResourceManager.GetString("PresetCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        internal static string PresetExpert {
            get {
                return ResourceManager.GetString("PresetExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate.
        /// </summary>
        internal static string PresetIntermediate {
            get {
                return ResourceManager.GetString("PresetIntermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini.
        /// </summary>
        internal static string PresetMini {
            get {
                return ResourceManager.GetString("PresetMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color:.
        /// </summary>
        internal static string SettingsAccentColor {
            get {
                return ResourceManager.GetString("SettingsAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color:.
        /// </summary>
        internal static string SettingsBackgroundColor {
            get {
                return ResourceManager.GetString("SettingsBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string SettingsButtonReset {
            get {
                return ResourceManager.GetString("SettingsButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string SettingsButtonShow {
            get {
                return ResourceManager.GetString("SettingsButtonShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string SettingsCategoryApp {
            get {
                return ResourceManager.GetString("SettingsCategoryApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string SettingsCategoryGame {
            get {
                return ResourceManager.GetString("SettingsCategoryGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        internal static string SettingsCategoryUI {
            get {
                return ResourceManager.GetString("SettingsCategoryUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default preset:.
        /// </summary>
        internal static string SettingsDefaultPreset {
            get {
                return ResourceManager.GetString("SettingsDefaultPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings:.
        /// </summary>
        internal static string SettingsResetSettings {
            get {
                return ResourceManager.GetString("SettingsResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset statistics:.
        /// </summary>
        internal static string SettingsResetStatistics {
            get {
                return ResourceManager.GetString("SettingsResetStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show welcome dialog:.
        /// </summary>
        internal static string SettingsShowWelcomeDialog {
            get {
                return ResourceManager.GetString("SettingsShowWelcomeDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to open a color chooser.
        /// </summary>
        internal static string SettingsTooltipColorChooser {
            get {
                return ResourceManager.GetString("SettingsTooltipColorChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Average Time: {1}.
        /// </summary>
        internal static string StatisticsCategoryAverageTime {
            get {
                return ResourceManager.GetString("StatisticsCategoryAverageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Games: {1}.
        /// </summary>
        internal static string StatisticsCategoryGames {
            get {
                return ResourceManager.GetString("StatisticsCategoryGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Defeats: {1}.
        /// </summary>
        internal static string StatisticsCategoryLost {
            get {
                return ResourceManager.GetString("StatisticsCategoryLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Mines: {1}.
        /// </summary>
        internal static string StatisticsCategoryMines {
            get {
                return ResourceManager.GetString("StatisticsCategoryMines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Performance: {1}%.
        /// </summary>
        internal static string StatisticsCategoryPerformance {
            get {
                return ResourceManager.GetString("StatisticsCategoryPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Shortest Time: {1}.
        /// </summary>
        internal static string StatisticsCategoryShortestTime {
            get {
                return ResourceManager.GetString("StatisticsCategoryShortestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Total Time: {1}.
        /// </summary>
        internal static string StatisticsCategoryTotalTime {
            get {
                return ResourceManager.GetString("StatisticsCategoryTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Victories: {1}.
        /// </summary>
        internal static string StatisticsCategoryWon {
            get {
                return ResourceManager.GetString("StatisticsCategoryWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string StatisticsPageGeneral {
            get {
                return ResourceManager.GetString("StatisticsPageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player can use hints to reveal a random square that contains a mine. This can be helpful in situations where the player is unsure about which squares to reveal next. Hints are limited and should be used sparingly..
        /// </summary>
        internal static string TutorialPage10Description {
            get {
                return ResourceManager.GetString("TutorialPage10Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hints.
        /// </summary>
        internal static string TutorialPage10Title {
            get {
                return ResourceManager.GetString("TutorialPage10Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player can pause the game at any time by clicking the pause button. This will stop the timer and prevent the player from accidentally revealing or flagging squares. The player can resume the game by clicking the resume button..
        /// </summary>
        internal static string TutorialPage11Description {
            get {
                return ResourceManager.GetString("TutorialPage11Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause and Resume.
        /// </summary>
        internal static string TutorialPage11Title {
            get {
                return ResourceManager.GetString("TutorialPage11Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You are now ready to play Minesweeper. Remember to use your hints wisely and keep an eye on the flag counter to avoid detonating any mines..
        /// </summary>
        internal static string TutorialPage12Description {
            get {
                return ResourceManager.GetString("TutorialPage12Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Luck!.
        /// </summary>
        internal static string TutorialPage12Title {
            get {
                return ResourceManager.GetString("TutorialPage12Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minesweeper is a single-player puzzle game where the objective is to clear a rectangular board containing hidden mines without detonating any of them. Players use logic to uncover safe squares and mark potential mine locations until the entire board is cleared, revealing the location of all the mines..
        /// </summary>
        internal static string TutorialPage1Description {
            get {
                return ResourceManager.GetString("TutorialPage1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minesweeper.
        /// </summary>
        internal static string TutorialPage1Title {
            get {
                return ResourceManager.GetString("TutorialPage1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left-click: Use this to reveal a square. If the square contains a mine, the game is over. If it is a blank square, it will reveal all adjacent blank squares until a number is reached. If it is a numbered square, it will reveal only that square..
        /// </summary>
        internal static string TutorialPage2Description {
            get {
                return ResourceManager.GetString("TutorialPage2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls: Left click.
        /// </summary>
        internal static string TutorialPage2Title {
            get {
                return ResourceManager.GetString("TutorialPage2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle-click: Use this to mark a square with a question mark. This is useful if you are unsure if the square contains a mine..
        /// </summary>
        internal static string TutorialPage3Description {
            get {
                return ResourceManager.GetString("TutorialPage3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls: Middle click.
        /// </summary>
        internal static string TutorialPage3Title {
            get {
                return ResourceManager.GetString("TutorialPage3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-click: Use this to flag a square. This indicates that the square contains a mine. Use the flag counter to keep track of how many mines are remaining on the board..
        /// </summary>
        internal static string TutorialPage4Description {
            get {
                return ResourceManager.GetString("TutorialPage4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls: Right click.
        /// </summary>
        internal static string TutorialPage4Title {
            get {
                return ResourceManager.GetString("TutorialPage4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game board is made up of a grid of squares. Some of these squares contain hidden mines. The player&apos;s objective is to reveal all non-mine squares without detonating any mines. The number of mines is predetermined and increases with the size of the board..
        /// </summary>
        internal static string TutorialPage5Description {
            get {
                return ResourceManager.GetString("TutorialPage5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Mechanics 1/3.
        /// </summary>
        internal static string TutorialPage5Title {
            get {
                return ResourceManager.GetString("TutorialPage5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a square is revealed, it will either be blank or contain a number. The numbers represent the number of mines in the eight surrounding squares. For example, if a square has the number &quot;3&quot; on it, it means that there are three mines in the eight squares surrounding that square..
        /// </summary>
        internal static string TutorialPage6Description {
            get {
                return ResourceManager.GetString("TutorialPage6Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Mechanics 2/3.
        /// </summary>
        internal static string TutorialPage6Title {
            get {
                return ResourceManager.GetString("TutorialPage6Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to use the numbers on the squares to make educated guesses and avoid detonating any mines!.
        /// </summary>
        internal static string TutorialPage7Description {
            get {
                return ResourceManager.GetString("TutorialPage7Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Mechanics 3/3.
        /// </summary>
        internal static string TutorialPage7Title {
            get {
                return ResourceManager.GetString("TutorialPage7Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is timed, and the timer begins counting as soon as the player clicks on their first square. The player&apos;s time is displayed on the game board, and the player&apos;s objective is to complete the game in the shortest amount of time possible..
        /// </summary>
        internal static string TutorialPage8Description {
            get {
                return ResourceManager.GetString("TutorialPage8Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string TutorialPage8Title {
            get {
                return ResourceManager.GetString("TutorialPage8Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player can flag squares that they believe contain mines. A counter keeps track of how many flags the player has set, and how many mines remain on the board. The player can use this information to make educated guesses and avoid detonating mines..
        /// </summary>
        internal static string TutorialPage9Description {
            get {
                return ResourceManager.GetString("TutorialPage9Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag Counter.
        /// </summary>
        internal static string TutorialPage9Title {
            get {
                return ResourceManager.GetString("TutorialPage9Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically chosen language: {0}.
        /// </summary>
        internal static string WelcomeChosenLanguage {
            get {
                return ResourceManager.GetString("WelcomeChosenLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start playing.
        /// </summary>
        internal static string WelcomeStartPlayingText {
            get {
                return ResourceManager.GetString("WelcomeStartPlayingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string WelcomeTutorialText {
            get {
                return ResourceManager.GetString("WelcomeTutorialText", resourceCulture);
            }
        }
    }
}
