# This workflow will build a C# Windows Forms desktop application built on .NET Core.

name: Build .NET Core Desktop Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Restore the application
    - name: Restore the application
      run: dotnet restore .\Minesweeper\Minesweeper.csproj

    # Compile the application using Publish-Profiles
    - name: Compile the application
      run: dotnet publish .\Minesweeper\Minesweeper.csproj -p:PublishProfile=LocalBuild_Portable
    
    # Upload the portable build: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Minesweeper_Debug
        path: .\Minesweeper\bin\Release\net7.0-windows\publish\portable
